image: haskell

tasks:
  - init: |
      stack setup
      mv ~/.stack /workspace/.stack
      ln -sv /workspace/.stack/ ~/.stack
      stack build
    command: |
      rm -rf ~/.stack
      ln -sv /workspace/.stack/ ~/.stack
      stack test

vscode:
  extensions:
    - haskell.haskell
