image: haskell

tasks:
  - init: |
      mkdir -p /workspace/.stack/
      ln -sv /workspace/.stack/ ~/.stack
      stack setup
      stack build
    command: |
      ln -sv /workspace/.stack/ ~/.stack
      stack test

vscode:
  extensions:
    - haskell.haskell
