name:                moded-logic
version:             0.1.0.0
github:              "davidar/moded-logic"
license:             BSD3
author:              "David A Roberts"
maintainer:          "d@vidr.cc"
copyright:           "2021 David A Roberts"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/davidar/moded-logic#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hspec
- logict
- megaparsec
- neat-interpolation
- picologic
- text

library:
  source-dirs: src

executables:
  moded-logic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moded-logic

tests:
  moded-logic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moded-logic
