name:                moded-logic
version:             0.1.0.0
github:              "davidar/moded-logic"
license:             BSD3
author:              "David A Roberts"
maintainer:          "d@vidr.cc"
copyright:           "2021 David A Roberts"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/davidar/moded-logic#readme>

dependencies:
- algebraic-graphs
- base >= 4.7 && < 5
- containers
- data-ordlist
- equivalence
- extra
- hspec
- hspec-expectations-pretty-diff
- logict
- MemoTrie
- megaparsec
- mtl
- neat-interpolation
- OneTuple
- picosat
- streamt
- template-haskell
- text
- vinyl

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  moded-logic-pp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - moded-logic
    - directory

tests:
  moded-logic-test:
    main:                Spec.hs
    source-dirs:
    - examples
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - moded-logic
    build-tools:
    - moded-logic-pp
